regexps:
  slim_html:
    # basic regexp for Slim HTML elements:
    #  - line must not contain ` {` (collision with SCSS) or `;` or `(` (collision with JS)
    #  - before: usually the HTML element, possibly with ID
    #  - classes: at least two classes prefixed with `.`
    regexp: '^(?![^=]*(?: {|[(;]))(?<before>\s*[a-z0-9_#-]*)(?<classes>(?:\.[a-z0-9_:\/-]+){2,})'
    file_extension: .slim
    class_prefix: .
    class_splitter: ''
  ruby_class_attribute:
    # regexp for the class attribute in ruby helpers in Slim:
    #   - before: the `class: "` attribute with quotation
    #   - classes: at least 2 classes joined by space(s)
    regexp: '(?<before>class: ")(?<classes>(?: *[a-z0-9_:\/-]+){2,})'
    file_extension: .slim
    class_prefix: ''
    class_splitter: ' '
variants_order:
  - custom # this is a special variant so that only custom variants have index 0
  - sm
  - md
  - lg
  - xl
  - 2xl
  - first
  - last
  - odd
  - even
  - hover
  - focus
  - focus-visible
  - group-hover
  - group-focus
  - focus-within
  - disabled
  - checked
  - active
  - visited
  - dark
  - motion-safe
  - motion-reduce

classes_order:
  # this is a special group so that custom classes get index 0
  custom:
    - custom
  layout:
    - static
    - fixed
    - absolute
    - relative
    - container
    - box-content
    - block
    - inline-block
    - inline
    - flex
    - inline-flex
    - table
    - table-cell
    - table-row
    - flow-root
    - grid
    - contents
    - hidden
    - float-right
    - float-left
    - float-none
    - clear-both
    - object-cover
    - object-center
    - overflow-auto
    - overflow-hidden
    - overflow-x-auto
    - overflow-y-auto
    - overflow-x-hidden
    - overflow-x-scroll
    - overflow-y-scroll
    - columns-2
    - /-?left-\d+/?\d*/
    - left-full
    - /-?right-\d+/?\d*/
    - right-full
    - inset-x-0
    - /-?top-\d+/?\d*/
    - top-full
    - /-?bottom-\d+/?\d*/
    - bottom-full
    - horizontal-centering
    - vertical-centering
    - centering-both
    - visible
    - invisible
    - z-0
    - z-10
    - z-20
    - z-30
    - z-40
    - z-50
    - z-99
    - z-100
    - z-101
    - z-102
    - z-103
    - z-999
    - z-9999
    - z-max
    - -z-1
  flexbox_and_grid:
    - flex-row
    - flex-row-reverse
    - flex-col
    - flex-col-reverse
    - flex-wrap
    - flex-nowrap
    - flex-1
    - flex-auto
    - flex-none
    - flex-grow
    - flex-shrink-0
    - basis-full
    - basis-1/3
    - order-first
    - grid-flow-col
    - grid-cols-1
    - grid-cols-2
    - grid-cols-3
    - grid-cols-6
    - grid-cols-12
    - grid-rows-7
    - grid-rows-9
    - grid-rows-11
    - col-span-2
    - col-span-3
    - col-span-4
    - col-span-5
    - col-span-6
    - col-span-11
    - col-span-full
    - col-start-2
    - row-start-1
    - row-end-3
    - row-end-5
    - gap-2
    - gap-3
    - gap-4
    - gap-8
    - gap-x-0
    - gap-x-2
    - gap-x-4
    - gap-x-8
    - gap-x-36
    - gap-y-2
    - gap-y-4
    - gap-y-6
    - justify-start
    - justify-end
    - justify-center
    - justify-between
    - justify-around
    - justify-self-start
    - justify-self-end
    - content-center
    - items-start
    - items-end
    - items-center
    - items-baseline
  sizing:
    - /w-\d+/?\d*/
    - w-auto
    - w-px
    - w-full
    - w-max
    - /min-w-\d+/?\d*/
    - min-w-full
    - max-w-none
    - max-w-3xs
    - max-w-2xs
    - max-w-xs
    - max-w-sm
    - max-w-md
    - max-w-lg
    - max-w-xl
    - max-w-2xl
    - max-w-3xl
    - max-w-4xl
    - max-w-5xl
    - max-w-6xl
    - max-w-7xl
    - max-w-full
    - /h-\d+/?\d*/
    - h-auto
    - h-px
    - h-full
    - /min-h-\d+/?\d*/
    - min-h-full
    - /max-h-\d+/?\d*/
    - max-h-full
    - aspect-ratio--16x9
    - aspect-ratio--7x4
  spacing:
    - /-?m-\d+/
    - mx-auto
    - /-?mx-\d+/
    - /-?my-\d+/
    - my-px
    - ml-auto
    - /-?ml-\d+/
    - /-?mr-\d+/
    - mt-auto
    - /-?mt-\d+/
    - mb-auto
    - /-?mb-\d+/
    - /p[xylrtb]?-\d+/
    - space-y-6
  typography:
    - font-sans
    - text-3xs
    - text-2xs
    - text-xs
    - text-sm
    - text-base
    - text-lg
    - text-xl
    - text-2xl
    - text-4xl
    - text-5xl
    - text-none
    - italic
    - not-italic
    - font-thin
    - font-extralight
    - font-light
    - font-normal
    - font-medium
    - font-semibold
    - font-bold
    - font-extrabold
    - font-black
    - tracking-tight
    - leading-6
    - leading-7
    - leading-8
    - leading-9
    - leading-none
    - leading-tight
    - leading-normal
    - leading-relaxed
    - leading-loose
    - list-none
    - list-disc
    - list-decimal
    - list-inside
    - list-square
    - text-left
    - text-center
    - text-right
    - text-black
    - underline
    - line-through
    - no-underline
    - decoration-wavy
    - uppercase
    - capitalize
    - truncate
    - align-baseline
    - align-top
    - align-middle
    - align-bottom
    - align-text-top
    - whitespace-normal
    - whitespace-nowrap
    - whitespace-pre-line
    - break-words
    - writing-mode-lr
    - writing-mode-revert
  colors:
    - bg-gradient-to-t
    - from-gray-50
    - to-transparent

    # TW background colors
    - bg-none
    - bg-current
    - bg-transparent
    - bg-black
    - /bg-black\/\d+/
    - bg-white
    - /bg-white\/\d+/
    - /bg-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)\/\d+/

    # TW text colors
    - text-inherit
    - text-current
    - text-transparent
    - text-black
    - /text-black\/\d+/
    - text-white
    - /text-white\/\d+/
    - /text-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)\/\d+/
  borders:
    - rounded-sm
    - rounded
    - rounded-md
    - rounded-lg
    - rounded-2xl
    - rounded-3xl
    - rounded-full
    - rounded-t-none
    - rounded-r-none
    - rounded-b-none
    - rounded-l-none
    - rounded-t
    - rounded-tr
    - rounded-tl
    - rounded-br
    - rounded-bl
    - rounded-tr-none
    - rounded-tl-none
    - rounded-br-none
    - rounded-bl-none
    - border
    - border-0
    - border-2
    - border-3
    - border-4
    - border-6
    - border-8
    - border-12
    - border-16
    - border-l
    - border-l-4
    - border-r
    - border-r-6
    - border-t
    - border-t-0
    - border-t-2
    - border-t-3
    - border-t-6
    - border-b
    - border-b-0
    - border-b-2
    - border-b-6
    - border-dashed
    - border-dotted
    - border-none
    - border-solid
    - border-cerulean-700
    - border-cerulean-800
    - border-underline-thin
    - border-underline-thick
    - border-underline-empty
    - outline-none
    - outline-0
    - ring-1
    - ring-black
    - ring-opacity-5
    - ring-offset-gray-100

    # TW border colors
    - border-inherit
    - border-current
    - border-transparent
    - border-black
    - /border-black\/\d+/
    - border-white
    - /border-white\/\d+/
    - /border-(slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)\/\d+/
  effects:
    - shadow
    - shadow-sm
    - shadow-md
    - shadow-lg
    - shadow-xl
    - shadow-2xl
    - shadow-inner
    - shadow-inner-1
    - shadow-3xl
    - shadow-4xl
    - shadow-grey
    - shadow-inner-2
    - shadow-white-2
    - shadow-grey-2
    - shadow-inner-3
    - shadow-inner-border
    - shadow-white
    - shadow-5xl
    - shadow-text-default
    - shadow-text-sm
    - shadow-text-lg
    - shadow-text-white
    - shadow-text-none
    - shadow-filter-grey
    - shadow-filter-white
    - shadow-filter-black
    - opacity-0
    - opacity-20
    - opacity-30
    - opacity-40
    - opacity-50
    - opacity-60
    - opacity-70
    - opacity-80
    - opacity-90
    - opacity-100
  tables:
    - border-collapse
    - table-auto
    - table-fixed
  animations:
    - transition-all
    - transition
    - transition-colors
    - transition-opacity
    - transition-transform
    - transition-top
    - transition-max-w
    - transition-max-h
    - duration-200
    - duration-300
    - duration-500
    - duration-700
    - delay-500
    - ease-linear
    - ease-in
    - ease-in-out
    - animate-pulse
    - animate-ping
    - animate-ellipsis
    - animate-skeleton
    - transform
    - transform-gpu
    - transform-none
    - scale-150
    - -scale-100
    - -scale-x-100
    - scale-y-50
    - scale-y-75
    - rotate-30
    - rotate-45
    - rotate-90
    - rotate-180
    - -rotate-90
    - -rotate-12
    - translate-x-1/2
    - -translate-x-1/2
    - translate-y-1/2
    - -translate-y-1/2
    - -translate-y-1/10
    - cursor-default
    - cursor-pointer
    - cursor-help
    - pointer-events-none
    - pointer-events-auto
    - resize-none
    - resize-y
    - resize
    - scroll-m-12
    - dim
    - link
    - link-txt
    - links-inside
  filters:
    - filter
    - blur
    - drop-shadow
    - grayscale
