#!/usr/bin/env ruby

require "tailwind_sorter/sorter"

warn_only = false
config_file = "config/tailwind_sorter.yml"

while (arg = ARGV.shift)
  case arg
  when "-w"
    warn_only = true
  when "-c"
    config_file = ARGV.shift
  else
    file_name = arg
  end
end

begin
  TailwindSorter::Sorter.run(file_name, warn_only: warn_only, config_file: config_file)
rescue ArgumentError => e
  STDERR.puts e.message
  exit 1
end
