#!/usr/bin/env ruby

lib = File.expand_path(File.dirname(__FILE__) + '/../lib')
$LOAD_PATH.unshift(lib) if File.directory?(lib) && !$LOAD_PATH.include?(lib)

require "tailwind_sorter"

warn_only = false
config_file = "config/tailwind_sorter.yml"

while (arg = ARGV.shift)
  case arg
  when "-w"
    warn_only = true
  when "-c"
    config_file = ARGV.shift
  else
    ARGV.unshift(arg)
    break
  end
end

begin
  while (file_name = ARGV.shift)
    TailwindSorter::Sorter.run(file_name, warn_only: warn_only, config_file: config_file)
  end
rescue ArgumentError => e
  STDERR.puts e.message
  exit 1
end
