name: Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      matrix:
        ruby:
          - '3.3.0'
          - '3.2.2'
          - '3.1.4'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run RSpec tests
      run: bundle exec rspec
